FROM debian:buster-slim

RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER postgres

RUN /etc/init.d/postgresql start && \
    psql --command "CREATE USER b20bb005 WITH SUPERUSER PASSWORD 'toor';" && \
    createdb -O b20bb005 userdb && \
    /etc/init.d/postgresql stop

RUN echo "local all all trust" > /etc/postgresql/11/main/pg_hba.conf && \
    echo "host all all 127.0.0.1/32 trust" >> /etc/postgresql/11/main/pg_hba.conf && \
    echo "host all all ::1/128 trust" >> /etc/postgresql/11/main/pg_hba.conf && \
    echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/11/main/pg_hba.conf

EXPOSE 5432

VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

CMD ["/usr/lib/postgresql/11/bin/postgres", "-D", "/var/lib/postgresql/11/main", "-c", "config_file=/etc/postgresql/11/main/postgresql.conf"]
